" Generated by vim-plug
" Thu Dec 29 01:24:27 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['CompleteParameter.vim'].commit = 'addb1e3623d91999b18700f8b64624a817c6fbee'
silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['deoplete-clang'].commit = '2ea262e98edcb66e828f9077fcc844100320eb63'
silent! let g:plugs['deoplete-jedi'].commit = '4a13930764f3fbda1c06d7312d8ce2ff595d3274'
silent! let g:plugs['deoplete.nvim'].commit = '4e91c4d3d0aa7630bea7d7b7f5ac259356c1959d'
silent! let g:plugs['neoinclude.vim'].commit = '954cfc9dfdb303f2c2fa867b9cf949dd74512628'
silent! let g:plugs['nvim-lspconfig'].commit = '432935081337dbbbc80f4d0531868509624505df'
silent! let g:plugs['rainbow'].commit = '61f719aebe0dc5c3048330c50db72cfee1afdd34'

PlugUpdate!

